version: 1.0.{build}

image:
  - Ubuntu2004
  - Visual Studio 2022

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "20"
    - nodejs_version: "18"
    - nodejs_version: "16"
    - nodejs_version: "14"

test_script:
  - ps: Write-Host "jspurefix test script"    

for:
-
    matrix:
      only:
        - image: Visual Studio 2022
  
    clone_folder: c:\projects\jspf-md-demo
    install:
      - ps: Install-Product node $env:nodejs_version $env:platform
      - npm install

    build_script:
      - cmd: node --version
      - cmd: cd node_modules\jspurefix 
      - cmd: script\build.cmd
      - cmd: cd c:\projects\jspf-md-demo
      - cmd: npm install
      - cmd: node_modules\.bin\tsc --version
      - cmd: node_modules\.bin\tsc

    test_script:
      - cmd: npm run md-app
-        
    matrix:
      only:
        - image: Ubuntu2004
        - platform: x64
    clone_folder: /home/appveyor/projects/jspf-md-demo 
    
    install:
      - nvm install $nodejs_version
      - npm install

    build_script:
      - sh: node --version
      - sh: cd /home/appveyor/projects/jspf-md-demo
      - sh: ./node_modules/.bin/tsc --version
      - sh: ./node_modules/.bin/tsc
      - sh: npm run circular

    test_script:
      - sh: npm run md-app

