version: 1.0.{build}

image: 
  - Ubuntu
  - Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "16"
    - nodejs_version: "14"
    - nodejs_version: "12"

test_script:
  - ps: Write-Host "jspurefix test script"    

for:
-
    matrix:
      only:
        - image: Visual Studio 2017
  
    clone_folder: c:\projects\jspf-md-demo
    install:
      - ps: Install-Product node $env:nodejs_version $env:platform
      - npm install
    build_script:
      - node --version
      - cmd: node_modules\jspurefix\script\build.cmd
    test_script:
      - cmd: npm run md-app
-        
    matrix:
      only:
        - image: Ubuntu
        - platform: x64
    clone_folder: /home/appveyor/projects/jspf-md-demo 
    
    install:
      - nvm install $nodejs_version
      - npm install

    build_script:
      - node --version
      - sh: node_modules/.bin/tsc --version
      - sh: chmod 555 node_modules/jspurefix/script/build.sh
      - sh: node_modules/jspurefix/script/build.sh
      - sh: node_modules/.bin/tsc

    test_script:
      - sh: "npm run md-app"

