import { MsgView, IJsFixConfig, ISessionDescription } from 'jspurefix'
import { IInstrmtMDReqGrpNoRelatedSym, IMarketDataRequest, MsgTag, MsgType } from '../../types/FIX50SP2'
import { Md50Factory } from './md50-factory'
import { MdBaseServer } from '../../common/md-base-server'

// interfaces generated by compiler to make messages easy in an IDE

export class Md50Server extends MdBaseServer {
  private readonly mdFactory: Md50Factory = new Md50Factory()

  constructor (public readonly config: IJsFixConfig) {
    super(config)
  }

  protected onLogon (view: MsgView, user: string, password: string): boolean {
    const targetCompId: string = view.getTyped(MsgTag.TargetCompID) as string
    const template = this.config.description
    const newSession = {
      application: template.application,
      BeginString: template.BeginString,
      HeartBtInt: template.HeartBtInt,
      BodyLengthChars: template.BodyLengthChars,
      SenderSubID: template.SenderSubID,
      SenderCompId: targetCompId,
      TargetSubID: template.TargetSubID,
      TargetCompID: template.TargetCompID,
      Username: template.Username,
      Password: template.Password,
      ResetSeqNumFlag: template.ResetSeqNumFlag,
      Name: template.Name,
      LastReceivedSeqNum: template.LastReceivedSeqNum,
      LastSentSeqNum: template.LastSentSeqNum
    } as ISessionDescription
    this.config.description = newSession
    this.logger.info(`inject ${JSON.stringify(newSession, null, 4)} using client targetCompId ${targetCompId}`)
    return true
  }

  protected onApplicationMsg (msgType: string, view: MsgView): void {
    this.logger.info(`${view.toJson()}`)
    switch (msgType) {
      case MsgType.MarketDataRequest: {
        this.marketDataRequest(view)
        break
      }
      default: {
        this.logger.info(`unknown msgType ${msgType}`)
        break
      }
    }
  }

  private marketDataRequest (view: MsgView): void {
    const req: IMarketDataRequest = view.toObject() as IMarketDataRequest
    const noSym: (IInstrmtMDReqGrpNoRelatedSym[] | null) = req.InstrmtMDReqGrp?.NoRelatedSym ?? null
    if (noSym == null) return
    const symbol: string = noSym[0]?.Instrument?.Symbol ?? ''
    const id = req.MDReqID
    const price = 1.22759
    const snapshot = this.mdFactory.FullSnapshot(symbol, id, price)
    this.send(MsgType.MarketDataSnapshotFullRefresh, snapshot)
  }

  public sendNews (headline: string): void {
    this.send(MsgType.News, this.mdFactory.News(headline))
  }
}
