import { ITrdRegTimestamps } from './trd_reg_timestamps'

export interface IMDFullGrpNoMDEntries {
  MDEntryType: string// [1] 269 (String)
  MDEntryPx?: number// [2] 270 (Float)
  Currency?: string// [3] 15 (String)
  MDEntrySize?: number// [4] 271 (Float)
  SettlType?: string// [5] 63 (String)
  TrdRegTimestamps: ITrdRegTimestamps// [6] NoTrdRegTimestamps.768, TrdRegTimestamp.769 .. TrdRegTimestampOrigin.771
  MDEntryDate?: Date// [7] 272 (UtcDateOnly)
  MDEntryTime?: Date// [8] 273 (UtcTimeOnly)
  TickDirection?: string// [9] 274 (String)
  MDMkt?: string// [10] 275 (String)
  TradingSessionID?: string// [11] 336 (String)
  TradingSessionSubID?: string// [12] 625 (String)
  QuoteCondition?: string// [13] 276 (String)
  TradeCondition?: string// [14] 277 (String)
  MDEntryOriginator?: string// [15] 282 (String)
  LocationID?: string// [16] 283 (String)
  DeskID?: string// [17] 284 (String)
  OpenCloseSettlFlag?: string// [18] 286 (String)
  TimeInForce?: string// [19] 59 (String)
  ExpireDate?: Date// [20] 432 (LocalDate)
  ExpireTime?: Date// [21] 126 (UtcTimestamp)
  MinQty?: number// [22] 110 (Float)
  ExecInst?: string// [23] 18 (String)
  SellerDays?: number// [24] 287 (Int)
  OrderID?: string// [25] 37 (String)
  QuoteEntryID?: string// [26] 299 (String)
  MDEntryBuyer?: string// [27] 288 (String)
  MDEntrySeller?: string// [28] 289 (String)
  NumberOfOrders?: number// [29] 346 (Int)
  MDEntryPositionNo?: number// [30] 290 (Int)
  Scope?: string// [31] 546 (String)
  PriceDelta?: number// [32] 811 (Float)
  Text?: string// [33] 58 (String)
  EncodedTextLen?: number// [34] 354 (Length)
  EncodedText?: Buffer// [35] 355 (RawData)
}
